version: '3.8'
services:
  api:
    image: asgarovfarhad/spread-trading-indexer:1.0.1
    container_name: spread-trading-indexer
    build: ./
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      - DB_HOST=
      - DB_PASSWORD=
      - DB_USER=
      - DB_NAME=
    platform: linux/amd64
